os: linux
sudo: required
dist: trusty
language:
  - cpp

compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libgtest-dev

before_script:
- mkdir ~/robot-code
- mkdir ~/robot-install

- export ROBOT_CODE=~/robot-code
- export ROBOT_INSTALL=~/robot-install

- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo make
- sudo cp *.a /usr/lib

- cd $ROBOT_CODE
- git clone https://github.com/eigenteam/eigen-git-mirror.git
- cd eigen-git-mirror
- mkdir build
- cd build
- cmake ../
- sudo make install

- cd $ROBOT_CODE
- git clone https://github.com/oxfordcontrol/osqp.git
- cd osqp
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=$ROBOT_INSTALL -DUNITTESTS=OFF ../
- make install
- export osqp_DIR=$ROBOT_INSTALL

script:
# Link gcc-6 and g++-6 to their standard commands
- sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
# Export CC and CXX to tell cmake which compiler to use
- export CC=/usr/bin/gcc-6
- export CXX=/usr/bin/g++-6
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v && cmake --version
- cd $TRAVIS_BUILD_DIR
- mkdir build
- cd build
- cmake ../
- make
- make test
